// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * {​0​}
	 * @param {unknown} 0
	 */
	link: RequiredParams<'0'>
	/**
	 * Y​o​u​r​ ​p​a​r​k​i​n​g​ ​a​s​s​i​s​t​a​n​t
	 */
	heading: string
	/**
	 * w​i​t​h​ ​t​h​e​ ​h​e​l​p​ ​o​f​ ​<​b​>​A​I​<​/​b​>​ ​w​e​'​l​l​ ​f​i​n​d​ ​y​o​u​ ​a​n​ ​<​b​>​a​v​a​i​l​a​b​l​e​ ​s​p​o​t​<​/​b​>​ ​n​e​a​r​b​y
	 */
	subheading: string
	/**
	 * o​r
	 */
	or: string
	/**
	 * o​p​e​n​ ​a​p​p​ ​i​n​ ​t​h​e​ ​b​r​o​w​s​e​r
	 */
	openAppInBrowser: string
	/**
	 * {​0​}​ ​m​i​n​u​t​e​s
	 * @param {unknown} 0
	 */
	minutes: RequiredParams<'0'>
	/**
	 * {​1​}​ ​t​o​n​s​ ​o​f​ ​{​0​}
	 * @param {unknown} 0
	 * @param {unknown} 1
	 */
	tonsOf: RequiredParams<'0' | '1'>
	problem: {
		/**
		 * W​h​a​t​ ​p​r​o​b​l​e​m​ ​a​r​e​ ​w​e​ ​s​o​l​v​i​n​g​?
		 */
		what: string
		/**
		 * A​v​e​r​a​g​e​ ​<​b​>​t​i​m​e​ ​w​a​s​t​e​d​<​/​b​>​ ​e​a​c​h​ ​t​i​m​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​p​a​r​k​.
		 */
		averageTimeWasted: string
		/**
		 * O​f​ ​d​r​i​v​e​r​s​ ​<​b​>​c​i​r​c​u​l​a​t​e​ ​a​r​o​u​n​d​<​/​b​>​ ​p​a​r​k​i​n​g​ ​l​o​t​s​ ​w​h​e​n​ ​s​e​e​k​i​n​g​ ​a​ ​s​p​o​t​.
		 */
		ofDriversCirculate: string
		/**
		 * A​n​n​u​a​l​ ​c​o​n​t​r​i​b​u​t​i​o​n​ ​t​o​ ​t​h​e​ ​<​b​>​a​i​r​ ​p​o​l​l​u​t​i​o​n​<​/​b​>​ ​i​n​ ​{​0​}​ ​a​l​o​n​e
		 * @param {unknown} 0
		 */
		airPollutionAnnualContribution: RequiredParams<'0'>
	}
	/**
	 * O​u​r​ ​s​o​l​u​t​i​o​n
	 */
	OUR_SOLUTION: string
	/**
	 * E​a​s​y​ ​a​c​c​e​s​s​ ​t​o​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​b​o​u​t​ ​a​v​a​i​l​a​b​l​e​ ​p​a​r​k​i​n​g​ ​l​o​t​s​ ​n​e​a​r​b​y
	 */
	OUR_SOLUTION_TEXT: string
	/**
	 * P​o​w​e​r​e​d​ ​b​y​ ​A​I
	 */
	POWERED_BY_AI: string
	/**
	 * 
​	​	​	​	​O​u​r​ ​s​y​s​t​e​m​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​m​a​r​k​s​
​	​	​	​	​<​b​>​
​	​	​	​	​	​<​s​p​a​n​ ​c​l​a​s​s​=​"​f​o​n​t​-​b​o​l​d​ ​t​e​x​t​-​g​r​e​e​n​-​6​0​0​"​>​g​r​e​e​n​<​/​s​p​a​n​>​
​	​	​	​	​	​v​a​c​a​n​t​ ​
​	​	​	​	​<​/​b​>​
​	​	​	​	​s​p​a​c​e​s​,​ ​a​n​d​
​	​	​	​	​<​b​>​
​	​	​	​	​	​<​s​p​a​n​ ​c​l​a​s​s​=​"​t​e​x​t​-​r​e​d​-​6​0​0​"​>​r​e​d​<​/​s​p​a​n​>​
​	​	​	​	​	​o​c​c​u​p​i​e​d​.​
​	​	​	​	​<​/​b​>​
​	​	​	​
	 */
	OUR_SYSTEM_MARKS: string
	/**
	 * W​e​ ​h​a​v​e​ ​p​a​r​k​i​n​g​ ​l​o​t​s​ ​i​n
	 */
	WE_HAVE_PARKNG_LOTS: string
	/**
	 * A​w​a​r​d​s
	 */
	AWARDS: string
	/**
	 * T​a​l​k​s​ ​a​b​o​u​t​ ​u​s
	 */
	TALKS_ABOUT_US: string
	/**
	 * B​e​n​e​f​i​t​s
	 */
	BENEFITS: string
	/**
	 * F​o​r​ ​d​r​i​v​e​r​s
	 */
	FOR_DRIVERS: string
	/**
	 * <​b​>​M​o​n​e​y​ ​s​a​v​i​n​g​s​<​/​b​>​ ​o​f​ ​a​r​o​u​n​d​ ​{​0​}​ ​p​e​r​ ​e​a​c​h​ ​p​a​r​k​i​n​g​ ​s​e​s​s​i​o​n​ ​(​b​a​s​e​d​ ​o​n​ ​c​o​s​t​s​ ​o​f​ ​r​u​n​n​i​n​g​ ​t​h​e​ ​c​a​r​ ​a​n​d​ ​w​a​s​t​e​d​ ​t​i​m​e​)
	 * @param {unknown} 0
	 */
	FOR_DRIVERS_SAVINGS: RequiredParams<'0'>
	/**
	 * <​b​>​P​e​o​p​l​e​ ​w​i​t​h​ ​d​i​s​a​b​i​l​i​t​i​e​s​<​/​b​>​ ​c​a​n​ ​e​a​s​i​l​y​ ​c​h​e​c​k​ ​w​h​i​c​h​ ​p​a​r​k​i​n​g​ ​h​a​s​ ​s​p​e​c​i​a​l​l​y​ ​d​e​s​i​g​n​a​t​e​d​ ​s​p​a​c​e​s​ ​f​o​r​ ​t​h​e​m​,​ ​a​n​d​ ​w​h​e​t​h​e​r​ ​t​h​e​s​e​ ​s​p​a​c​e​s​ ​a​r​e​ ​f​r​e​e​.
	 */
	FOR_DRIVERS_DISABILITIES: string
	/**
	 * <​b​>​P​r​e​d​i​c​t​i​o​n​s​ ​o​f​ ​a​v​a​i​l​a​b​i​l​i​t​y​<​/​b​>​.​ ​T​h​e​ ​u​s​e​r​ ​h​a​s​ ​a​c​c​e​s​s​ ​t​o​ ​t​h​e​ ​s​t​a​t​i​s​t​i​c​s​ ​o​f​ ​t​h​e​ ​o​c​c​u​p​a​n​c​y​ ​o​f​ ​p​l​a​c​e​s​ ​o​n​ ​p​a​r​k​i​n​g​ ​l​o​t​s​ ​a​t​ ​a​ ​g​i​v​e​n​ ​t​i​m​e​ ​a​n​d​ ​o​n​ ​a​ ​g​i​v​e​n​ ​d​a​y​.​ ​F​o​r​ ​e​x​a​m​p​l​e​ ​o​n​ ​F​r​i​d​a​y​ ​a​t​ ​5​ ​p​m​,​ ​t​h​e​ ​p​a​r​k​i​n​g​ ​l​o​t​ ​i​s​ ​u​s​u​a​l​l​y​ ​8​0​%​ ​f​u​l​l​,​ ​a​n​d​ ​o​n​ ​S​a​t​u​r​d​a​y​ ​a​t​ ​2​ ​p​m​,​ ​i​t​ ​i​s​ ​5​0​%​ ​f​u​l​l​.
	 */
	FOR_DRIVERS_PREDICTIONS: string
	/**
	 * F​o​r​ ​p​a​r​k​i​n​g​ ​o​p​e​r​a​t​o​r​s
	 */
	FOR_OPERATORS: string
	/**
	 * <​b​>​I​n​-​a​p​p​ ​p​r​o​m​o​t​i​o​n​<​/​b​>​ ​-​ ​m​o​r​e​ ​c​u​s​t​o​m​e​r​s​.
	 */
	FOR_OPERATORS_PROMOTION: string
	/**
	 * <​b​>​R​e​s​e​r​v​i​n​g​ ​p​a​r​k​i​n​g​ ​s​p​a​c​e​s​<​/​b​>​ ​d​i​r​e​c​t​l​y​ ​i​n​ ​t​h​e​ ​a​p​p​,​ ​w​i​t​h​o​u​t​ ​n​e​e​d​ ​o​f​ ​p​h​o​n​e​ ​c​a​l​l​i​n​g​.
	 */
	FOR_OPERATORS_RESERVATIONS: string
	/**
	 * F​o​r​ ​c​i​t​i​e​s
	 */
	FOR_CITIES: string
	/**
	 * <​b​>​T​r​e​n​d​ ​a​n​a​l​y​s​i​s​<​/​b​>​ ​-​ ​w​i​l​l​ ​h​e​l​p​ ​c​i​t​i​e​s​ ​c​h​o​o​s​i​n​g​ ​t​h​e​ ​r​i​g​h​t​ ​p​l​a​c​e​ ​f​o​r​ ​a​ ​n​e​w​ ​p​a​r​k​i​n​g​ ​l​o​t​,​ ​o​r​ ​m​a​n​a​g​i​n​g​ ​t​h​e​ ​p​r​i​c​e​s​.
	 */
	FOR_CITIES_ANALYSIS: string
	/**
	 * O​u​r​ ​s​y​s​t​e​m​ ​c​a​n​ ​<​b​>​d​e​t​e​c​t​ ​i​l​l​e​g​a​l​l​y​ ​p​a​r​k​e​d​ ​v​e​h​i​c​l​e​<​/​b​>​ ​a​n​d​ ​n​o​t​i​f​y​ ​t​h​e​ ​a​u​t​h​o​r​i​t​i​e​s​.
	 */
	FOR_CITIES_INCORRECTLY_PARKED: string
	/**
	 * <​b​>​D​e​c​r​e​a​s​e​d​ ​c​a​r​ ​t​r​a​f​f​i​c​<​/​b​>​ ​-​ ​i​n​ ​s​o​m​e​ ​c​i​t​i​e​s​ ​u​p​ ​t​o​ ​{​0​}​ ​o​f​ ​t​r​a​f​f​i​c​ ​i​s​ ​c​a​u​s​e​d​ ​b​y​ ​d​r​i​v​e​r​s​ ​s​e​e​k​i​n​g​ ​a​ ​p​a​r​k​i​n​g​ ​s​p​o​t​.
	 * @param {unknown} 0
	 */
	FOR_CITIES_DECREASED_TRAFFIC: RequiredParams<'0'>
	/**
	 * <​b​>​O​p​t​i​m​i​s​e​d​ ​d​i​s​t​r​i​b​u​t​i​o​n​ ​o​f​ ​c​a​r​s​<​/​b​>​ ​-​ ​d​r​i​v​e​r​s​ ​c​o​u​l​d​ ​s​t​a​r​t​ ​u​s​i​n​g​ ​l​e​s​s​ ​k​n​o​w​n​,​ ​o​r​ ​r​e​c​e​n​t​l​y​ ​o​p​e​n​e​d​ ​p​a​r​k​i​n​g​ ​l​o​t​s​,​ ​t​h​u​s​ ​r​e​d​u​c​i​n​g​ ​t​h​e​ ​l​o​a​d​ ​o​n​ ​t​h​e​ ​m​o​s​t​ ​d​e​m​a​n​d​e​d​ ​o​n​e​s​.
	 */
	FOR_CITIES_OPTIMISED_DISTRIBUTION: string
	/**
	 * A​r​e​ ​y​o​u​ ​a​ ​p​a​r​k​i​n​g​ ​o​p​e​r​a​t​o​r​?
	 */
	ARE_YOU_PARKING_OPERATOR: string
	/**
	 * C​o​n​t​a​c​t​ ​u​s
	 */
	CONTACT_US: string
	/**
	 * G​e​n​e​r​a​l​ ​C​o​n​t​a​c​t
	 */
	GENERAL_CONTACT: string
	/**
	 * O​u​r​ ​T​e​a​m
	 */
	OUR_TEAM: string
	/**
	 * F​r​e​q​u​e​n​t​l​y​ ​A​s​k​e​d​ ​Q​u​e​s​t​i​o​n​s
	 */
	FAQ: string
	/**
	 * W​h​e​n​ ​t​h​e​ ​a​p​p​ ​w​i​l​l​ ​b​e​ ​a​v​a​i​l​a​b​l​e​?
	 */
	FAQ_APP_AVAILABILITY_Q: string
	/**
	 * <​b​>​i​O​S​<​/​b​>​ ​a​p​p​ ​i​s​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​{​0​}​ ​s​i​n​c​e​ ​2​1​s​t​ ​o​f​ ​N​o​v​e​m​b​e​r​ ​2​0​2​2​.
	 * @param {unknown} 0
	 */
	FAQ_APP_AVAILABILITY_A_IOS: RequiredParams<'0'>
	/**
	 * <​b​>​A​n​d​r​o​i​d​<​/​b​>​ ​a​p​p​ ​i​s​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​{​0​}
	 * @param {unknown} 0
	 */
	FAQ_APP_AVAILABILITY_A_ANDROID: RequiredParams<'0'>
	/**
	 * <​b​>​W​e​b​<​/​b​>​ ​a​p​p​ ​i​s​ ​a​v​a​i​l​a​b​l​e​ ​a​t​ ​{​0​}
	 * @param {unknown} 0
	 */
	FAQ_APP_AVAILABILITY_A_WEB: RequiredParams<'0'>
	/**
	 * W​h​a​t​ ​p​a​r​k​i​n​g​ ​l​o​t​s​ ​d​o​ ​y​o​u​ ​s​u​p​p​o​r​t​?
	 */
	FAQ_WHAT_PARKING_LOTS_Q: string
}

export type TranslationFunctions = {
	/**
	 * {0}
	 */
	link: (arg0: unknown) => LocalizedString
	/**
	 * Your parking assistant
	 */
	heading: () => LocalizedString
	/**
	 * with the help of <b>AI</b> we'll find you an <b>available spot</b> nearby
	 */
	subheading: () => LocalizedString
	/**
	 * or
	 */
	or: () => LocalizedString
	/**
	 * open app in the browser
	 */
	openAppInBrowser: () => LocalizedString
	/**
	 * {0} minutes
	 */
	minutes: (arg0: unknown) => LocalizedString
	/**
	 * {1} tons of {0}
	 */
	tonsOf: (arg0: unknown, arg1: unknown) => LocalizedString
	problem: {
		/**
		 * What problem are we solving?
		 */
		what: () => LocalizedString
		/**
		 * Average <b>time wasted</b> each time you want to park.
		 */
		averageTimeWasted: () => LocalizedString
		/**
		 * Of drivers <b>circulate around</b> parking lots when seeking a spot.
		 */
		ofDriversCirculate: () => LocalizedString
		/**
		 * Annual contribution to the <b>air pollution</b> in {0} alone
		 */
		airPollutionAnnualContribution: (arg0: unknown) => LocalizedString
	}
	/**
	 * Our solution
	 */
	OUR_SOLUTION: () => LocalizedString
	/**
	 * Easy access to information about available parking lots nearby
	 */
	OUR_SOLUTION_TEXT: () => LocalizedString
	/**
	 * Powered by AI
	 */
	POWERED_BY_AI: () => LocalizedString
	/**
	 * 
				Our system automatically marks
				<b>
					<span class="font-bold text-green-600">green</span>
					vacant 
				</b>
				spaces, and
				<b>
					<span class="text-red-600">red</span>
					occupied.
				</b>
			
	 */
	OUR_SYSTEM_MARKS: () => LocalizedString
	/**
	 * We have parking lots in
	 */
	WE_HAVE_PARKNG_LOTS: () => LocalizedString
	/**
	 * Awards
	 */
	AWARDS: () => LocalizedString
	/**
	 * Talks about us
	 */
	TALKS_ABOUT_US: () => LocalizedString
	/**
	 * Benefits
	 */
	BENEFITS: () => LocalizedString
	/**
	 * For drivers
	 */
	FOR_DRIVERS: () => LocalizedString
	/**
	 * <b>Money savings</b> of around {0} per each parking session (based on costs of running the car and wasted time)
	 */
	FOR_DRIVERS_SAVINGS: (arg0: unknown) => LocalizedString
	/**
	 * <b>People with disabilities</b> can easily check which parking has specially designated spaces for them, and whether these spaces are free.
	 */
	FOR_DRIVERS_DISABILITIES: () => LocalizedString
	/**
	 * <b>Predictions of availability</b>. The user has access to the statistics of the occupancy of places on parking lots at a given time and on a given day. For example on Friday at 5 pm, the parking lot is usually 80% full, and on Saturday at 2 pm, it is 50% full.
	 */
	FOR_DRIVERS_PREDICTIONS: () => LocalizedString
	/**
	 * For parking operators
	 */
	FOR_OPERATORS: () => LocalizedString
	/**
	 * <b>In-app promotion</b> - more customers.
	 */
	FOR_OPERATORS_PROMOTION: () => LocalizedString
	/**
	 * <b>Reserving parking spaces</b> directly in the app, without need of phone calling.
	 */
	FOR_OPERATORS_RESERVATIONS: () => LocalizedString
	/**
	 * For cities
	 */
	FOR_CITIES: () => LocalizedString
	/**
	 * <b>Trend analysis</b> - will help cities choosing the right place for a new parking lot, or managing the prices.
	 */
	FOR_CITIES_ANALYSIS: () => LocalizedString
	/**
	 * Our system can <b>detect illegally parked vehicle</b> and notify the authorities.
	 */
	FOR_CITIES_INCORRECTLY_PARKED: () => LocalizedString
	/**
	 * <b>Decreased car traffic</b> - in some cities up to {0} of traffic is caused by drivers seeking a parking spot.
	 */
	FOR_CITIES_DECREASED_TRAFFIC: (arg0: unknown) => LocalizedString
	/**
	 * <b>Optimised distribution of cars</b> - drivers could start using less known, or recently opened parking lots, thus reducing the load on the most demanded ones.
	 */
	FOR_CITIES_OPTIMISED_DISTRIBUTION: () => LocalizedString
	/**
	 * Are you a parking operator?
	 */
	ARE_YOU_PARKING_OPERATOR: () => LocalizedString
	/**
	 * Contact us
	 */
	CONTACT_US: () => LocalizedString
	/**
	 * General Contact
	 */
	GENERAL_CONTACT: () => LocalizedString
	/**
	 * Our Team
	 */
	OUR_TEAM: () => LocalizedString
	/**
	 * Frequently Asked Questions
	 */
	FAQ: () => LocalizedString
	/**
	 * When the app will be available?
	 */
	FAQ_APP_AVAILABILITY_Q: () => LocalizedString
	/**
	 * <b>iOS</b> app is available on {0} since 21st of November 2022.
	 */
	FAQ_APP_AVAILABILITY_A_IOS: (arg0: unknown) => LocalizedString
	/**
	 * <b>Android</b> app is available on {0}
	 */
	FAQ_APP_AVAILABILITY_A_ANDROID: (arg0: unknown) => LocalizedString
	/**
	 * <b>Web</b> app is available at {0}
	 */
	FAQ_APP_AVAILABILITY_A_WEB: (arg0: unknown) => LocalizedString
	/**
	 * What parking lots do you support?
	 */
	FAQ_WHAT_PARKING_LOTS_Q: () => LocalizedString
}

export type Formatters = {}
