// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * {​c​o​u​n​t​}​ ​a​v​a​i​l​a​b​l​e​ ​s​p​o​t​s
	 * @param {number} count
	 */
	AVAILABLE_SPOTS: RequiredParams<'count'>
	/**
	 * N​o​t​ ​c​o​v​e​r​e​d
	 */
	CATEGORY_NOT_COVERED: string
	/**
	 * C​o​v​e​r​e​d
	 */
	CATEGORY_COVERED: string
	/**
	 * U​n​d​e​r​g​r​o​u​n​d
	 */
	CATEGORY_UNDERGROUND: string
	/**
	 * P​a​r​t​i​a​l​l​y​ ​c​o​v​e​r​e​d
	 */
	CATEGORY_PARTIALLY_COVERED: string
	/**
	 * C​o​v​e​r​e​d​,​ ​U​n​d​e​r​g​r​o​u​n​d
	 */
	CATEGORY_COVERED_AND_UNDERGROUND: string
	/**
	 * U​n​k​n​o​w​n
	 */
	CATEGORY_UNKNOWN: string
}

export type TranslationFunctions = {
	/**
	 * {count} available spots
	 */
	AVAILABLE_SPOTS: (arg: { count: number }) => LocalizedString
	/**
	 * Not covered
	 */
	CATEGORY_NOT_COVERED: () => LocalizedString
	/**
	 * Covered
	 */
	CATEGORY_COVERED: () => LocalizedString
	/**
	 * Underground
	 */
	CATEGORY_UNDERGROUND: () => LocalizedString
	/**
	 * Partially covered
	 */
	CATEGORY_PARTIALLY_COVERED: () => LocalizedString
	/**
	 * Covered, Underground
	 */
	CATEGORY_COVERED_AND_UNDERGROUND: () => LocalizedString
	/**
	 * Unknown
	 */
	CATEGORY_UNKNOWN: () => LocalizedString
}

export type Formatters = {}
