version: "3.8"
services:
  caddy:
    image: caddy:latest
    container_name: wheretopark_caddy
    restart: unless-stopped
    ports:
      - "1234:1234"
    volumes:
      - $PWD/Caddyfile.dev:/etc/caddy/Caddyfile

  collector:
    container_name: wheretopark_collector
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/collector/Dockerfile
    environment:
      CCTV_MODEL_PATH: /opt/wheretopark/model.onnx
      LOG_LEVEL: trace
    volumes:
      - $HOME/.local/share/wheretopark:/opt/wheretopark
    ports:
      - "8001:8080"

volumes:
