version: "3.8"
services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "8000:8000"
    command: 
      - start
      - --log=trace
      - --user=${SURREALDB_USER}
      - --pass=${SURREALDB_PASSWORD}
    networks:
      - net
      - traefik-public
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 10
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.surrealdb-http.rule=Host(`${SURREALDB_DOMAIN?SURREALDB_DOMAIN not set}`)
        - traefik.http.routers.surrealdb-http.entrypoints=http
        - traefik.http.routers.surrealdb-http.middlewares=https-redirect
        - traefik.http.routers.surrealdb-https.rule=Host(`${SURREALDB_DOMAIN?SURREALDB_DOMAIN not set}`)
        - traefik.http.routers.surrealdb-https.entrypoints=https
        - traefik.http.routers.surrealdb-https.tls=true
        - traefik.http.routers.surrealdb-https.tls.certresolver=le
        - traefik.http.services.surrealdb.loadbalancer.server.port=80

  tristar:
    container_name: tristar
    image: ghcr.io/wheretopark/tristar:latest
    networks:
      - net
    environment:
      DATABASE_URL: ws://surrealdb:8000
      DATABASE_NAME: production
      DATABASE_USER: ${SURREALDB_USER}
      DATABASE_PASSWORD: ${SURREALDB_PASSWORD}
    depends_on:
      - surrealdb

  webapp:
    container_name: webapp
    image: ghcr.io/wheretopark/webapp:latest
    ports:
      - "3000:3000"
    networks:
      - net
    environment:
      SECRET_DATABASE_USER: ${SURREALDB_USER}
      SECRET_DATABASE_PASSWORD: ${SURREALDB_PASSWORD}
      SECRET_DATABASE_NAME: production
      SECRET_DATABASE_URL: http://surrealdb:8000
      PUBLIC_MAPBOX_ACCESS_TOKEN: pk.eyJ1IjoiZ2JhcmFuc2tpIiwiYSI6ImNsNmh4ZW9hZTBxaG4zY282MzAzbWhqbnAifQ.8_G9b7-m8n0kMr4O0-2mhQ
    depends_on:
      - surrealdb

networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true