version: "3.8"
services:
  collector:
    container_name: wheretopark_collector
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/collector/Dockerfile
    ports:
      - "8081:8080"

  cctv:
    container_name: wheretopark_cctv
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/cctv/Dockerfile
    environment:
      MODEL: /opt/wheretopark/cctv/model.onnx
    volumes:
      - $HOME/.local/share/wheretopark/cctv:/opt/wheretopark/cctv
      - $HOME/.cache/wheretopark/cctv:/root/.cache/wheretopark/cctv
    ports:
      - "8082:8080"

  webapp:
    container_name: wheretopark_webapp
    restart: unless-stopped
    build:
      context: ./webapp
    ports:
      - "3000:3000"
    networks:
      - default
      - public
    environment:
      PUBLIC_MAPBOX_ACCESS_TOKEN: pk.eyJ1IjoiZ2JhcmFuc2tpIiwiYSI6ImNsNmh4ZW9hZTBxaG4zY282MzAzbWhqbnAifQ.8_G9b7-m8n0kMr4O0-2mhQ
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  public:
    external: true
