version: "3.8"
services:
  authorization:
    ports:
      - "5002:80"
    build:
      context: .
      dockerfile: authorization/Dockerfile
    environment:
      PORT: 80
      APPLICATION_CLIENT_ID: ${APPLICATION_CLIENT_ID?APPLICATION_CLIENT_ID not set}
      APPLICATION_CLIENT_SECRET: ${APPLICATION_CLIENT_SECRET?APPLICATION_CLIENT_SECRET not set}
      PROVIDER_CLIENT_ID: ${PROVIDER_CLIENT_ID?PROVIDER_CLIENT_ID not set}
      PROVIDER_CLIENT_SECRET: ${PROVIDER_CLIENT_SECRET?PROVIDER_CLIENT_SECRET not set}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - net

  storekeeper:
    image: wheretopark-storekeeper
    ports:
      - "5001:80"
    environment:
      PORT: 80
      STORE_URI: redis://redis
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - net
    depends_on:
      - authorization
      - redis

#  providers-tristar:
#    image: wheretopark-provider-tristar
#    networks:
#      - net
#    environment:
#      STOREKEEPER_URL: ${STOREKEEPER_URL?STOREKEEPER_URL not set}
#      AUTHORIZATION_URL: ${AUTHORIZATION_URL?AUTHORIZATION_URL not set}
#      CLIENT_ID: ${OAUTH_CLIENT_ID?OAUTH_CLIENT_ID not set}
#      CLIENT_SECRET: ${OAUTH_CLIENT_SECRET?OAUTH_CLIENT_SECRET not set}
#    depends_on:
#      - storekeeper
#      - authorization

  redis:
    image: redis
    networks:
      - net

networks:
  net: