services:
  config:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./providers.json:/usr/share/nginx/html/providers
    ports:
      - "9000:80"
    labels:
      - "traefik.http.middlewares.wheretopark-config-redirect.replacepathregex.regex=/v1/providers"
      - "traefik.http.middlewares.wheretopark-config-redirect.replacepathregex.replacement=/v1/config/providers"
      - "traefik.http.middlewares.wheretopark-config-cors.headers.accesscontrolallowmethods=GET"
      - "traefik.http.middlewares.wheretopark-config-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.wheretopark-config-strip.stripprefixregex.regex=^\\/[^\\/]+\\/[^\\/]+"
      - "traefik.http.middlewares.wheretopark-config-content-type.headers.customresponseheaders.Content-Type=application/json"

      - "traefik.enable=true"
      - "traefik.http.routers.wheretopark-config.rule=Host(`api.wheretopark.app`) && (PathPrefix(`/v1/config`) || Path(`/v1/providers`))"
      - "traefik.http.routers.wheretopark-config.entrypoints=websecure"
      - "traefik.http.routers.wheretopark-config.middlewares=wheretopark-config-redirect,wheretopark-config-cors,wheretopark-config-strip,wheretopark-config-content-type"

  influxer:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/influxer/Dockerfile
    environment:
      LOG_LEVEL: debug
      SERVER_URL: "https://api.wheretopark.app"
      INFLUXDB_TOKEN: lj3YEMcRfKvtxM6mAkfdk8fkR5wgPt5ZB0KBhOtPOGDE0ZE_1V8jrv8LPMU1PMj_CjqHM-9QnnYb0j52s7iTeA==

  cctv:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/cctv/Dockerfile
    environment:
      PORT: 8080
      LOG_LEVEL: debug
      CCTV_MODEL_PATH: /opt/wheretopark/model.onnx
      GIN_MODE: release
    volumes:
      - $HOME/.local/share/wheretopark:/opt/wheretopark
      - $HOME/.cache/wheretopark:/root/.cache/wheretopark
    ports:
      - "9001:8080"
    labels:
      - "traefik.http.middlewares.wheretopark-cctv-cors.headers.accesscontrolallowmethods=GET"
      - "traefik.http.middlewares.wheretopark-cctv-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.wheretopark-cctv-strip.stripprefix.prefixes=/v1/provider/cctv"

      - "traefik.enable=true"
      - "traefik.http.routers.wheretopark-cctv.rule=Host(`api.wheretopark.app`) && PathPrefix(`/v1/provider/cctv`)"
      - "traefik.http.routers.wheretopark-cctv.entrypoints=websecure"
      - "traefik.http.routers.wheretopark-cctv.middlewares=wheretopark-cctv-cors,wheretopark-cctv-strip"


  gdansk:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/gdansk/Dockerfile
    environment:
      PORT: 8080
      LOG_LEVEL: debug
    ports:
      - "9002:8080"
    labels:
      - "traefik.http.middlewares.wheretopark-gdansk-cors.headers.accesscontrolallowmethods=GET"
      - "traefik.http.middlewares.wheretopark-gdansk-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.wheretopark-gdansk-strip.stripprefix.prefixes=/v1/provider/gdansk"

      - "traefik.enable=true"
      - "traefik.http.routers.wheretopark-gdansk.rule=Host(`api.wheretopark.app`) && PathPrefix(`/v1/provider/gdansk`)"
      - "traefik.http.routers.wheretopark-gdansk.entrypoints=websecure"
      - "traefik.http.routers.wheretopark-gdansk.middlewares=wheretopark-gdansk-cors,wheretopark-gdansk-strip"

  gdynia:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/gdynia/Dockerfile
    environment:
      PORT: 8080
      LOG_LEVEL: debug
    ports:
      - "9003:8080"
    labels:
      - "traefik.http.middlewares.wheretopark-gdynia-cors.headers.accesscontrolallowmethods=GET"
      - "traefik.http.middlewares.wheretopark-gdynia-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.wheretopark-gdynia-strip.stripprefix.prefixes=/v1/provider/gdynia"

      - "traefik.enable=true"
      - "traefik.http.routers.wheretopark-gdynia.rule=Host(`api.wheretopark.app`) && PathPrefix(`/v1/provider/gdynia`)"
      - "traefik.http.routers.wheretopark-gdynia.entrypoints=websecure"
      - "traefik.http.routers.wheretopark-gdynia.middlewares=wheretopark-gdynia-cors,wheretopark-gdynia-strip"

  glasgow:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/glasgow/Dockerfile
    environment:
      PORT: 8080
      LOG_LEVEL: debug
    ports:
      - "9004:8080"
    labels:
      - "traefik.http.middlewares.wheretopark-glasgow-cors.headers.accesscontrolallowmethods=GET"
      - "traefik.http.middlewares.wheretopark-glasgow-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.wheretopark-glasgow-strip.stripprefix.prefixes=/v1/provider/glasgow"

      - "traefik.enable=true"
      - "traefik.http.routers.wheretopark-glasgow.rule=Host(`api.wheretopark.app`) && PathPrefix(`/v1/provider/glasgow`)"
      - "traefik.http.routers.wheretopark-glasgow.entrypoints=websecure"
      - "traefik.http.routers.wheretopark-glasgow.middlewares=wheretopark-glasgow-cors,wheretopark-glasgow-strip"

  lacity:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/lacity/Dockerfile
    environment:
      PORT: 8080
      LOG_LEVEL: debug
    ports:
      - "9005:8080"
    labels:
      - "traefik.http.middlewares.wheretopark-lacity-cors.headers.accesscontrolallowmethods=GET"
      - "traefik.http.middlewares.wheretopark-lacity-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.wheretopark-lacity-strip.stripprefix.prefixes=/v1/provider/lacity"

      - "traefik.enable=true"
      - "traefik.http.routers.wheretopark-lacity.rule=Host(`api.wheretopark.app`) && PathPrefix(`/v1/provider/lacity`)"
      - "traefik.http.routers.wheretopark-lacity.entrypoints=websecure"
      - "traefik.http.routers.wheretopark-lacity.middlewares=wheretopark-lacity-cors,wheretopark-lacity-strip"

  poznan:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/poznan/Dockerfile
    environment:
      PORT: 8080
      LOG_LEVEL: debug
    ports:
      - "9006:8080"
    labels:
      - "traefik.http.middlewares.wheretopark-poznan-cors.headers.accesscontrolallowmethods=GET"
      - "traefik.http.middlewares.wheretopark-poznan-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.wheretopark-poznan-strip.stripprefix.prefixes=/v1/provider/poznan"

      - "traefik.enable=true"
      - "traefik.http.routers.wheretopark-poznan.rule=Host(`api.wheretopark.app`) && PathPrefix(`/v1/provider/poznan`)"
      - "traefik.http.routers.wheretopark-poznan.entrypoints=websecure"
      - "traefik.http.routers.wheretopark-poznan.middlewares=wheretopark-poznan-cors,wheretopark-poznan-strip"


  warsaw:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/warsaw/Dockerfile
    environment:
      PORT: 8080
      LOG_LEVEL: debug
    ports:
      - "9007:8080"
    labels:
      - "traefik.http.middlewares.wheretopark-warsaw-cors.headers.accesscontrolallowmethods=GET"
      - "traefik.http.middlewares.wheretopark-warsaw-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.wheretopark-warsaw-strip.stripprefix.prefixes=/v1/provider/warsaw"

      - "traefik.enable=true"
      - "traefik.http.routers.wheretopark-warsaw.rule=Host(`api.wheretopark.app`) && PathPrefix(`/v1/provider/warsaw`)"
      - "traefik.http.routers.wheretopark-warsaw.entrypoints=websecure"
      - "traefik.http.routers.wheretopark-warsaw.middlewares=wheretopark-warsaw-cors,wheretopark-warsaw-strip"

networks:
  default:
    name: public
    external: true
