version: "3.8"
services:
  storekeeper:
    image: gbaranski/wheretopark-storekeeper
    ports:
      - "3458:8080"
    environment:
      - PORT=8080
    networks:
      - net
      - traefik-public
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost/health-check"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 3
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.wheretopark-storekeeper-http.rule=Host(`${STOREKEEPER_DOMAIN?Variable not set}`)
        - traefik.http.routers.wheretopark-storekeeper-http.entrypoints=http
        - traefik.http.routers.wheretopark-storekeeper-http.middlewares=https-redirect
        - traefik.http.routers.wheretopark-storekeeper-https.rule=Host(`${STOREKEEPER_DOMAIN?Variable not set}`)
        - traefik.http.routers.wheretopark-storekeeper-https.entrypoints=https
        - traefik.http.routers.wheretopark-storekeeper-https.tls=true
        - traefik.http.routers.wheretopark-storekeeper-https.tls.certresolver=le
        - traefik.http.services.wheretopark-storekeeper.loadbalancer.server.port=8080

  # providers-tristar:
  #  image: wheretopark-providers-tristar
  #  networks:
  #    - net
  #  environment:
  #    - STOREKEEPER_URL=http://storekeeper
  #  depends_on:
  #    - storekeeper

networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
