version: "3"
services:
  storekeeper:
    container_name: wheretopark-storekeeper
    image: wheretopark-storekeeper
    restart: unless-stopped
    ports:
      - 3458:80
    environment:
      - PORT=80
    networks:
      - default
      - web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health-check"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 2s

  # provider-tristar:
  #   container_name: wheretopark-provider-tristar
  #   build:
  #     context: ~/code/wheretopark/server
  #     args:
  #       PACKAGE_NAME: wheretopark-provider-tristar
  #   restart: unless-stopped
  #   environment:
  #     - STOREKEEPER_URL=http://wheretopark-storekeeper
  #   depends_on:
  #     - storekeeper

networks:
  web:
    external: true
