version: "3.8"
services:
  caddy:
    image: caddy:latest
    container_name: wheretopark_caddy
    restart: unless-stopped
    ports:
      - "1234:1234"
    volumes:
      - $PWD/Caddyfile.dev:/etc/caddy/Caddyfile

  collector:
    container_name: wheretopark_collector
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/collector/Dockerfile
    environment:
      LOG_LEVEL: trace
    ports:
      - "8001:8080"

  cctv:
    container_name: wheretopark_cctv
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/cctv/Dockerfile
    environment:
      MODEL: /opt/wheretopark/cctv/model.onnx
      LOG_LEVEL: trace
    volumes:
      - $HOME/.local/share/wheretopark/cctv:/opt/wheretopark/cctv
    ports:
      - "8002:8080"

volumes:
  influxdb_data: