version: "3.8"
services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "8000:8000"
    command: 
      - start
      - --log=trace
      - --user=root
      - --pass=root
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 10

  tristar:
    container_name: tristar
    build:
      context: .
      dockerfile: providers/tristar/Dockerfile
    depends_on:
      - surrealdb
    environment:
      DATABASE_URL: ws://surrealdb:8000
      DATABASE_NAME: development
      DATABASE_USER: root
      DATABASE_PASSWORD: root

  webapp:
    container_name: webapp
    ports:
      - "5173:5173"
    build: 
      context: ./webapp
      dockerfile: Dockerfile.dev
    environment:
      SECRET_DATABASE_USER: root
      SECRET_DATABASE_PASSWORD: root
      SECRET_DATABASE_URL: http://surrealdb:8000
      SECRET_DATABASE_NAME: development
      PUBLIC_MAPBOX_ACCESS_TOKEN: pk.eyJ1IjoiZ2JhcmFuc2tpIiwiYSI6ImNsNmh4ZW9hZTBxaG4zY282MzAzbWhqbnAifQ.8_G9b7-m8n0kMr4O0-2mhQ
    depends_on:
      - surrealdb
    volumes:
      - ./webapp/src:/app/src:ro