version: "3.8"
services:
  caddy:
    image: caddy:latest
    container_name: wheretopark_caddy
    restart: unless-stopped
    ports:
      - "1234:1234"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile

  collector:
    container_name: wheretopark_collector
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/collector/Dockerfile

  cctv:
    container_name: wheretopark_cctv
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/cctv/Dockerfile
    environment:
      MODEL: /opt/wheretopark/cctv/model.onnx
    volumes:
      - $HOME/.local/share/wheretopark/cctv:/opt/wheretopark/cctv
      - $HOME/.cache/wheretopark/cctv:/root/.cache/wheretopark/cctv