version: "3.8"
services:
  caddy:
    image: caddy:latest
    container_name: wheretopark_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile

  collector:
    container_name: wheretopark_collector
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/collector/Dockerfile
    environment:
      MODEL_PATH: /opt/wheretopark/model.onnx
      GIN_MODE: release
    volumes:
      - $HOME/.local/share/wheretopark:/opt/wheretopark
      - $HOME/.cache/wheretopark:/root/.cache/wheretopark