version: "3.8"
services:
  collector:
    container_name: wheretopark_collector
    env_file: .env
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/collector/Dockerfile
    environment:
      DATABASE_URL: ${SURREALDB_URL}
      DATABASE_NAME: production
      DATABASE_USER: ${SURREALDB_USER}
      DATABASE_PASSWORD: ${SURREALDB_PASSWORD}

  cctv:
    container_name: wheretopark_cctv
    env_file: .env
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/cctv/Dockerfile
    environment:
      DATABASE_URL: ${SURREALDB_URL}
      DATABASE_NAME: production
      DATABASE_USER: ${SURREALDB_USER}
      DATABASE_PASSWORD: ${SURREALDB_PASSWORD}
      MODEL: /opt/wheretopark/cctv/model.onnx
    volumes:
      - $HOME/.local/share/wheretopark/cctv:/opt/wheretopark/cctv
      - $HOME/.cache/wheretopark/cctv:/root/.cache/wheretopark/cctv

networks:
  public:
    external: true
