version: "3.8"
services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle/users.yml:/data/users.yml
    environment:
      DOZZLE_AUTH_PROVIDER: simple

  collector:
    container_name: wheretopark_collector
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/collector/Dockerfile
    environment:
      CCTV_MODEL_PATH: /opt/wheretopark/model.onnx
      GIN_MODE: release
    volumes:
      - $HOME/.local/share/wheretopark:/opt/wheretopark
      - $HOME/.cache/wheretopark:/root/.cache/wheretopark
