parking-lots:
  1:
    resources:
      - mailto:sekretariat@zdiz.gdynia.pl
      - tel:+48-58-761-2000
      - tel:+48-58-761-2001
      - https://www.zdiz.gdynia.pl/parkowanie/oplaty/
    total-spots:
      CAR: 78
    features:
      - UNCOVERED
    comment:
      pl:
        Parking znajduje się w śródmiejskiej strefie płatnego parkowania.
        
        Opłaty za postój pojazdu WD sa określone na https://www.zdiz.gdynia.pl/parkowanie/oplaty/
      
        Bezpłatny postój w niedzielę z identyfikatorem Mieszkańca Gdyni
      
        Opłat nie pobiera się 1 i 6 stycznia, w niedzielę i poniedziałek Świąt Wielkanocnych, 25 i 26 grudnia
      
        Długoterminowe abonamenty są określone na https://www.zdiz.gdynia.pl/parkowanie/oplaty/
    payment-methods:
      - CASH
      - CARD
      - CONTACTLESS
      - MOBILE
    rules:
      - hours: Mo-Su 08:00-20:00
        pricing:
          - duration: PT1H
            price: 5.50
          - duration: PT2H
            price: 12.10
          - duration: PT3H
            price: 20.00
          - duration: PT1H
            price: 5.50
            repeating: true
      - hours: Mo-Su 20:00-08:00
        pricing:
          - duration: PT1H
            price: 0
            repeating: true
      - hours: 24/7
        applies:
          - CAR_ELECTRIC
          - CAR_DISABLED
        pricing:
          - duration: PT1H
            price: 0
            repeating: true

  2:
    resources:
      - mailto:sekretariat@zdiz.gdynia.pl
      - tel:+48-58-761-2000
      - tel:+48-58-761-2001
      - https://www.zdiz.gdynia.pl/parkowanie/oplaty/
    total-spots:
      CAR: 50
    features:
      - UNCOVERED
    comment:
      pl:
        Parking znajduje się w śródmiejskiej strefie płatnego parkowania.
        
        Opłaty za postój pojazdu WD sa określone na https://www.zdiz.gdynia.pl/parkowanie/oplaty/
        
        Bezpłatny postój w niedzielę z identyfikatorem Mieszkańca Gdyni
        
        Opłat nie pobiera się 1 i 6 stycznia, w niedzielę i poniedziałek Świąt Wielkanocnych, 25 i 26 grudnia
        
        Długoterminowe abonamenty są określone na https://www.zdiz.gdynia.pl/parkowanie/oplaty/
    payment-methods:
      - CASH
      - CARD
      - CONTACTLESS
      - MOBILE
    rules:
      - hours: Mo-Su 08:00-20:00
        pricing:
          - duration: PT1H
            price: 5.50
          - duration: PT2H
            price: 12.10
          - duration: PT3H
            price: 20.00
          - duration: PT1H
            price: 5.50
            repeating: true
      - hours: Mo-Su 20:00-08:00
        pricing:
          - duration: PT1H
            price: 0
            repeating: true
      - hours: 24/7
        applies:
          - CAR_ELECTRIC
          - CAR_DISABLED
        pricing:
          - duration: PT1H
            price: 0
            repeating: true


  3:
    resources:
      - mailto:sekretariat@zdiz.gdynia.pl
      - tel:+48-58-761-2000
      - tel:+48-58-761-2001
      - https://www.zdiz.gdynia.pl/parkowanie/oplaty/
    total-spots:
      CAR: 50
    features:
      - UNCOVERED
    comment:
      pl:
        Parking znajduje się w śródmiejskiej strefie płatnego parkowania.
        
        Opłaty za postój pojazdu WD sa określone na https://www.zdiz.gdynia.pl/parkowanie/oplaty/
        
        Bezpłatny postój w niedzielę z identyfikatorem Mieszkańca Gdyni
        
        Opłat nie pobiera się 1 i 6 stycznia, w niedzielę i poniedziałek Świąt Wielkanocnych, 25 i 26 grudnia
        
        Długoterminowe abonamenty są określone na https://www.zdiz.gdynia.pl/parkowanie/oplaty/
    payment-methods:
      - CASH
      - CARD
      - CONTACTLESS
      - MOBILE
    rules:
      - hours: Mo-Su 08:00-20:00
        pricing:
          - duration: PT1H
            price: 5.50
          - duration: PT2H
            price: 12.10
          - duration: PT3H
            price: 20.00
          - duration: PT1H
            price: 5.50
            repeating: true
      - hours: Mo-Su 20:00-08:00
        pricing:
          - duration: PT1H
            price: 0
            repeating: true
      - hours: 24/7
        applies:
          - CAR_ELECTRIC
          - CAR_DISABLED
        pricing:
          - duration: PT1H
            price: 0
            repeating: true


  4:
    resources:
      - mailto:sekretariat@zdiz.gdynia.pl
      - tel:+48-58-761-2000
      - tel:+48-58-761-2001
      - https://www.zdiz.gdynia.pl/parkowanie/oplaty/
    total-spots:
      CAR: 75
    features:
      - UNCOVERED
    comment:
      pl:
        Parking znajduje się w strefie płatnego parkowania.
        
        Opłaty za postój pojazdu WD sa określone na https://www.zdiz.gdynia.pl/parkowanie/oplaty/
        
        Długoterminowe abonamenty są określone na https://www.zdiz.gdynia.pl/parkowanie/oplaty/
    payment-methods:
      - CASH
      - CARD
      - CONTACTLESS
      - MOBILE
    rules:
      - hours: Mo-Su 08:00-20:00, Dec 24-25 08:00-14:00
        pricing:
          - duration: PT1H
            price: 3.90
          - duration: PT2H
            price: 8.50
          - duration: PT3H
            price: 14.00
          - duration: PT1H
            price: 3.90
            repeating: true
      - hours: Mo-Su 20:00-08:00, Dec 24-25 14:00-08:00
        pricing:
          - duration: PT1H
            price: 0
            repeating: true