parking-lots:
  "1":
    resources:
      - mailto:galeria@galeriabaltycka.pl
      - tel:+48-58-521-85-52
      - https://www.galeriabaltycka.pl/o-centrum/dojazd-parkingi/parkingi/
    total-spots: 1100
    features:
      - COVERED
      - UNCOVERED
    rules:
      - weekdays: MONDAY-SATURDAY
        hours: 08:00-22:00
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT2H
            price: 2
          - duration: PT3H
            price: 3
          - duration: P1D
            price: 25
          - duration: PT1H
            price: 4
            repeating: true
      - weekdays: SUNDAY-SUNDAY
        hours: 09:00-21:00
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT2H
            price: 2
          - duration: PT3H
            price: 3
          - duration: P1D
            price: 25
          - duration: PT1H
            price: 4
            repeating: true

  "2":
    resources:
      - mailto:biuro@gchmanhattan.pl
      - tel:+48-58-767-70-16
      - https://gchmanhattan.pl/o-centrum/
    features:
      - UNDERGROUND
    total-spots: 360
    # TODO: Add Sunday rule, in Poland on Sundays, this Gallery are only open sometimes
    rules:
      - weekdays: MONDAY-FRIDAY
        hours: 09:00-21:00
        pricing:
          - duration: PT30M
            price: 0
          - duration: PT1H
            price: 4
            repeating: true
      - weekdays: SATURDAY-SATURDAY
        hours: 09:00-21:00
        pricing:
          - duration: PT30M
            price: 0
          - duration: PT1H
            price: 4
            repeating: true

  "3":
    resources:
      - mailto:parkingi@apcoa.pl
      - tel:+48-22-354-83-80
      - https://www.apcoa.pl/parking-w/gdansk-1/polsat-plus-arena-gdansk-p4-ul-pok-lechii-gdansk/
      - https://www.apcoa.pl/parking-w/gdansk-1/polsat-plus-arena-gdansk-p3-ul-pok-lechii-gdansk/
    features:
      - UNCOVERED
    total-spots: 1914
    rules:
      - weekdays: null
        hours: null
        pricing:
          - duration: PT30M
            price: 1
          - duration: PT1H
            price: 4
          - duration: PT1H
            price: 4
            repeating: true

  "4":
    resources:
      - mailto:parkingi@apcoa.pl
      - tel:+48-22-354-83-80
      - https://www.apcoa.pl/parking-w/gdansk-1/amber-expo-gdansk-ul-zaglowa-11/
    features:
      - UNCOVERED
    total-spots: 510
    rules:
      - weekdays: null
        hours: null
        pricing:
          # You may take this every 4 hours
          - duration: PT30M
            price: 1
          - duration: PT1H
            price: 4
          - duration: PT1H
            price: 4
            repeating: true

  "5":
    resources:
      - mailto:info@madison.gda.pl
      - tel:+48-58-766-75-39
      - https://madison.gda.pl/pl/parking
    features:
      - UNDERGROUND
    total-spots: 117
    rules:
      - weekdays: MONDAY-FRIDAY
        hours: 08:00-22:00
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT2H
            price: 5
          - duration: PT3H
            price: 10
          - duration: PT1H
            price: 8
            repeating: true
      - weekdays: SATURDAY-SATURDAY
        hours: 08:00-22:00
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT2H
            price: 0
          - duration: PT3H
            price: 5
          - duration: PT1H
            price: 8
            repeating: true
      - weekdays: SATURDAY-SATURDAY
        hours: 08:00-22:00
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT2H
            price: 0
          - duration: PT3H
            price: 5
          - duration: PT1H
            price: 5
            repeating: true
      # Night pricing
      - weekdays: null
        hours: 22:00-08:00
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT1H
            price: 1
            repeating: true

  "7":
    resources:
      - mailto:e.gazda@amuz.gda.pl
      - tel:+48-58-300-92-06
      - https://www.amuz.gda.pl/akademia/infrastruktura/parking,108
    features:
      - UNCOVERED
    total-spots: 215 # TODO: Not sure??
    rules:
      - weekdays: null
        hours: null
        pricing:
          - duration: PT30M
            price: 0
          - duration: PT1H
            price: 6
            repeating: true

  "14":
    resources:
      - https://ecs.gda.pl/title,Parking_,pid,601.htm
    features:
      - UNCOVERED
    total-spots: 287
    rules:
      - weekdays: null
        hours: 06:00-22:00
        pricing:
          - duration: PT30M
            price: 0
          - duration: PT1H
            price: 4
          - duration: PT2H
            price: 8
          - duration: PT3H
            price: 9
          - duration: PT1H
            price: 10
            repeating: true

  "15":
    resources:
      - mailto:bartlomiej.jablonski@carpark.com.pl
      - tel:+48-661-552-882
      - https://galeriametropolia.pl/parking/
    features:
      - UNCOVERED
      - COVERED
    total-spots: 1500
    rules:
      - weekdays: null
        hours: null
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT2H
            price: 3
          - duration: PT3H
            price: 7
          # TODO: Make that available only on the UNCOVERED parking lot
          - duration: PT24H
            price: 17
          - duration: PT1H
            price: 5
            repeating: true

  "17":
    resources:
      - mailto:parking@forumgdansk.pl
      - tel:+48-661-551-882
      - https://forumgdansk.pl/pl/przydatne-informacje/parking
    features:
      - COVERED
      - UNCOVERED
    total-spots: 1008
    rules:
      - weekdays: null
        hours: null
        pricing:
          - duration: PT30M
            price: 0
          - duration: PT1H
            price: 3
          - duration: PT2H
            price: 8
          - duration: PT3H
            price: 13
          - duration: PT1H
            price: 10
            repeating: true

  "18":
    resources:
      - mailto:parkingi@apcoa.pl
      - tel:+48-22-354-83-80
      - https://www.apcoa.pl/parking-w/gdansk-1/gdansk-ul-blekitna/
    features:
      - UNCOVERED
    total-spots: 197
    rules:
      - weekdays: MONDAY-SUNDAY
        hours: 09:00-19:00
        pricing:
          - duration: P1D
            price: 10

  "19":
    resources: []
    features:
      - UNCOVERED
    total-spots: 60
    rules:
      - weekdays: MONDAY-SUNDAY
        hours: 09:00-19:00
        pricing:
          - duration: P1D
            price: 10

  # TODO: Verify
  "21":
    resources: []
    features:
      - UNCOVERED
    total-spots: 340
    rules:
      - weekdays: MONDAY-SUNDAY
        hours: 09:00-19:00
        pricing:
          - duration: P1D
            price: 10