parking-lots:
  "1":
    emails:
      - galeria@galeriabaltycka.pl
    phone-numbers:
      - +48 58 521 85 52
    websites:
      - https://www.galeriabaltycka.pl/o-centrum/dojazd-parkingi/parkingi/
    total-spots: 1100
    features:
      - COVERED
      - UNCOVERED
    rules:
      - weekdays: monday-saturday
        hours: 08:00-22:00
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT2H
            price: 2
          - duration: PT3H
            price: 3
          - duration: P1D
            price: 25
          - duration: PT1H
            price: 4
            repeating: true
      - weekdays: sunday-sunday
        hours: 09:00-21:00
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT2H
            price: 2
          - duration: PT3H
            price: 3
          - duration: P1D
            price: 25
          - duration: PT1H
            price: 4
            repeating: true

  "2":
    emails:
      - biuro@gchmanhattan.pl
    phone-numbers:
      - +48 58 767 70 16
    websites:
      - https://gchmanhattan.pl/o-centrum/
    features:
      - UNDERGROUND
    total-spots: 360
    # TODO: Add Sunday rule, in Poland on Sundays, this Gallery are only open sometimes
    rules:
      - weekdays: monday-friday
        hours: 09:00-21:00
        pricing:
          - duration: PT30M
            price: 0
          - duration: PT1H
            price: 4
            repeating: true
      - weekdays: saturday-saturday
        hours: 09:00-21:00
        pricing:
          - duration: PT30M
            price: 0
          - duration: PT1H
            price: 4
            repeating: true

  "3":
    emails:
      - parkingi@apcoa.pl
    phone-numbers:
      - +48 22 354 83 80
    websites:
      - https://www.apcoa.pl/parking-w/gdansk-1/polsat-plus-arena-gdansk-p4-ul-pok-lechii-gdansk/
      - https://www.apcoa.pl/parking-w/gdansk-1/polsat-plus-arena-gdansk-p3-ul-pok-lechii-gdansk/
    features:
      - UNCOVERED
    total-spots: 1914
    rules:
      - weekdays: null
        hours: null
        pricing:
          - duration: PT30M
            price: 1
          - duration: PT1H
            price: 4
          - duration: PT1H
            price: 4
            repeating: true

  "4":
    emails:
      - parkingi@apcoa.pl
    phone-numbers:
      - +48 22 354 83 80
    websites:
      - https://www.apcoa.pl/parking-w/gdansk-1/amber-expo-gdansk-ul-zaglowa-11/
    features:
      - UNCOVERED
    total-spots: 510
    rules:
      - weekdays: null
        hours: null
        pricing:
          # You may take this every 4 hours
          - duration: PT30M
            price: 1
          - duration: PT1H
            price: 4
          - duration: PT1H
            price: 4
            repeating: true

  "5":
    emails:
      - info@madison.gda.pl
    phone-numbers:
      - +48 58 766 75 39
    websites:
      - https://madison.gda.pl/pl/parking
    features:
      - UNDERGROUND
    total-spots: 117
    rules:
      - weekdays: monday-friday
        hours: 08:00-22:00
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT2H
            price: 5
          - duration: PT3H
            price: 10
          - duration: PT1H
            price: 8
            repeating: true
      - weekdays: saturday-saturday
        hours: 08:00-22:00
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT2H
            price: 0
          - duration: PT3H
            price: 5
          - duration: PT1H
            price: 8
            repeating: true
      - weekdays: saturday-saturday
        hours: 08:00-22:00
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT2H
            price: 0
          - duration: PT3H
            price: 5
          - duration: PT1H
            price: 5
            repeating: true
      # Night pricing
      - weekdays: null
        hours: 22:00-08:00
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT1H
            price: 1
            repeating: true

  "7":
    emails:
      - e.gazda@amuz.gda.pl
    phone-numbers:
      - +48 58 300 92 06
    websites:
      - https://www.amuz.gda.pl/akademia/infrastruktura/parking,108
    features:
      - UNCOVERED
    total-spots: 215 # TODO: Not sure??
    rules:
      - weekdays: null
        hours: null
        pricing:
          - duration: PT30M
            price: 0
          - duration: PT1H
            price: 6
            repeating: true

  "14":
    emails: []
    phone-numbers: []
    websites:
      - https://ecs.gda.pl/title,Parking_,pid,601.htm
    features:
      - UNCOVERED
    total-spots: 287
    rules:
      - weekdays: null
        hours: 06:00-22:00
        pricing:
          - duration: PT30M
            price: 0
          - duration: PT1H
            price: 4
          - duration: PT2H
            price: 8
          - duration: PT3H
            price: 9
          - duration: PT1H
            price: 10
            repeating: true

  "15":
    emails:
      - bartlomiej.jablonski@carpark.com.pl
    phone-numbers:
      - +48 661 552 882
    websites:
      - https://galeriametropolia.pl/parking/
    features:
      - UNCOVERED
      - COVERED
    total-spots: 1500
    rules:
      - weekdays: null
        hours: null
        pricing:
          - duration: PT1H
            price: 0
          - duration: PT2H
            price: 3
          - duration: PT3H
            price: 7
          # TODO: Make that available only on the UNCOVERED parking lot
          - duration: PT24H
            price: 17
          - duration: PT1H
            price: 5
            repeating: true

  "17":
    emails:
      - parking@forumgdansk.pl
    phone-numbers:
      - +48 661 551 882
    websites:
      - https://forumgdansk.pl/pl/przydatne-informacje/parking
    features:
      - COVERED
      - UNCOVERED
    total-spots: 1008
    rules:
      - weekdays: null
        hours: null
        pricing:
          - duration: PT30M
            price: 0
          - duration: PT1H
            price: 3
          - duration: PT2H
            price: 8
          - duration: PT3H
            price: 13
          - duration: PT1H
            price: 10
            repeating: true

  "18":
    emails:
      - parkingi@apcoa.pl
    phone-numbers:
      - +48 22 354 83 80
    websites:
      - https://www.apcoa.pl/parking-w/gdansk-1/gdansk-ul-blekitna/
    features:
      - UNCOVERED
    total-spots: 197
    rules:
      - weekdays: monday-sunday
        hours: 09:00-19:00
        pricing:
          - duration: P1D
            price: 10

  "19":
    emails: []
    phone-numbers: []
    websites: []
    features:
      - UNCOVERED
    total-spots: 60
    rules:
      - weekdays: monday-sunday
        hours: 09:00-19:00
        pricing:
          - duration: P1D
            price: 10

  # TODO: Verify
  "21":
    emails: []
    phone-numbers: []
    websites: []
    features:
      - UNCOVERED
    total-spots: 340
    rules:
      - weekdays: monday-sunday
        hours: 09:00-19:00
        pricing:
          - duration: P1D
            price: 10