# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Webapp CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "webapp/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./webapp
          file: ./webapp/Dockerfile
          tags: ghcr.io/wheretopark/webapp:latest
          platforms: "linux/amd64,linux/arm64"